### ISSUE TITLE
12/10 issue(仮)

### ISSUE THREAD

**Issue by izumoo1** [delihiros/raspi-car#1]
- リモコンの操作はどうする？　ユースケース図では真ん中の「リモコンを操作する」部分はどうやってロボットを動かすのか？
- 要求部分が用件ではないのか？ラジコンを走らせてどうしたいのかが目的＝要求
- 目的が「おもちゃ」なら走るが要求で通るかもしれないけど、「走る」事は要求ではないのではないか？
  もう少し、細かく要求を決定しなければならない。
  要件：センサで情報を取得したい
  要求：その為にどうするのか？
  拡張性を目的とすると、要求が「走る」事でも大丈夫。
  目的を詳しく決定する。
- ＵＣ図、センサーを載せかえるのか？組み込まれているのか？
  ロボットやリモコンがどのような機能を別々に持っているのかを書く。
- 人がロボットに対してする操作、リモコンがロボットにどうするのか
- 文章化する（目的やゴール）

**Comment by monocan** [comment]
仮としてまとめて書いてあるので、細かいissueとしてissureを登録しなおしておきます。
