### ISSUE TITLE
シーケンス図の作成

### ISSUE THREAD

**Issue by izumoo1** [delihiros/raspi-car#13]
シーケンス図が必要です。

**Comment by izumoo1** [comment]
シーケンス図を作成しました
![img_0758](https://cloud.githubusercontent.com/assets/14990412/12138671/d7add642-b49d-11e5-87d2-0799356a887c.JPG)

**Comment by monocan** [comment]
![sequence.sqd.jpg](https://files.zenhub.io/568d28095b4d69034a9455a4)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by monocan** [comment]
![sequence](https://cloud.githubusercontent.com/assets/15242938/12145146/d4755aa4-b4cf-11e5-9b17-c0f8c5277e2d.jpg)
