### ISSUE TITLE
目的を決める

### ISSUE THREAD

**Issue by monocan** [delihiros/raspi-car#2]
・１～２文で文章化する。

・項目は１つか２つに絞る

・一般の人がわかるようにわかりやすくかつ詳細も伝わるように。
　　　例えばおもちゃやったら何歳が使う

**Comment by monocan** [comment]
福島などの原発の近くなど、人間が侵入できないが平坦さが確保された場所において、環境情報を測定する（放射能など）。

**Comment by forestcats0214** [comment]
福島などのような危険な場所において、人間が進入できない。その周囲の環境情報を取得する拡張性のあるロボットを作成する。

**Comment by izumoo1** [comment]
福島のような危険な場所において、人間が進入できない場所周囲の環境情報を取得する、拡張性のあるロボットを作成する。
