### ISSUE TITLE
ゴールを決める

### ISSUE THREAD

**Issue by monocan** [delihiros/raspi-car#3]
・１～２文で文章化

・項目をしぼる

・わかりやすく詳細が伝わるように
　　　　例えば今のままやと手軽が何かわからない

**Comment by forestcats0214** [comment]
リモートで操作でき、前後左右に移動できるロボットを作成する。このロボットは目的に応じて機能拡張することができる。本プロジェクトでは機能拡張の一例として、画像情報を取得し、リモートでユーザに送信する。
