### ISSUE TITLE
高位の要求を決める

### ISSUE THREAD

**Issue by monocan** [delihiros/raspi-car#4]
・目的、ゴールを詰めてから考える

・今のままやと要求部分が用件ではないのか？ラジコンを走らせてどうしたいのかが目的＝要求
　　拡張性を目的とすると、要求が「走る」事でも大丈夫。

・要求は顧客やユーザからの要求。
　要件は開発者目線で必要な機能。

**Comment by delihiros** [comment]
# 要求
- ユーザは安全な場所から，リアルタイムにロボットを操作しロボットから情報を受信することができる．
- 一定の知識を持つユーザはプログラミングや電子工作をすることで，ロボットの機能を拡張することができる．
