### ISSUE TITLE
あらかじめ実現可能な要求を絞っておく

### ISSUE THREAD

**Issue by monocan** [delihiros/raspi-car#68]

**Comment by izumoo1** [comment]
実現可能な要求としては、撮影、移動、拡張の３つがあります。
今回は、ロボットが見えているが近づく事が出来ない場所へ移動し、付近を撮影する
事を要求にすれば良いのではないかと思う。

**Comment by izumoo1** [comment]
例えば、人間は通れないがロボットは通れるフェンス越しとか、有毒ガスの中とか

**Comment by monocan** [comment]
wikiに

# プロジェクトの目的
- 周囲の環境情報を取得する、拡張性のあるロボットを作成する。使用場所としてはロボットは目視できるが、人は近づく事が出来ない場所（例：フェンス越し、有毒ガスの中）を想定する。
