### ISSUE TITLE
テストの実施、wikiに記載

### ISSUE THREAD

**Issue by monocan** [delihiros/raspi-car#69]

**Comment by izumoo1** [comment]
テスト項目表 [作成日時] 2016-02-03 [作成者] REN HU

[実施日時] 2016-02-04 [実施者] 山本　雄貴

[ユースケース名] ユーザが上ボタンを押す [確認項目] ロボットが前に動く

[テスト結果] ok

[ユースケース名] ユーザが下ボタンを押す [確認項目] ロボットが後ろに動く

[テスト結果] ok

[ユースケース名] ユーザが左ボタンを押す [確認項目] ロボットが左折する

[テスト結果] ok

[ユースケース名] ユーザが右ボタンを押す [確認項目] ロボットが右折する

[テスト結果] ok

[ユースケース名] ユーザがPC画面を見る [確認項目] ロボットがその時点の写真を撮り、PC画面上でユーザが画像を確認する

[テスト結果] ok(但し、遅い？)
