### ISSUE TITLE
ユースケース図、テスト検証を画像カメラ取得ボタンをなくす方向で変更

### ISSUE THREAD

**Issue by monocan** [delihiros/raspi-car#70]

**Comment by monocan** [comment]
![default](https://cloud.githubusercontent.com/assets/15242938/12808259/c49e4f56-cb58-11e5-937c-a6f59a7b56af.png)

**Comment by monocan** [comment]
[ユースケース名] ユーザがPC画面を見る [確認項目] ロボットがその時点の写真を撮り、PC画面上でユーザが画像を確認する

**Comment by izumoo1** [comment]
大丈夫です
